# Generated by Django 5.2 on 2026-01-07 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Объект')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Старая цена')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_top', models.BooleanField(default=False, verbose_name='Топовое направление')),
                ('flight_cost_per_one', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость перелета на одного')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Страна')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('country_image', models.ImageField(upload_to='country_img/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='RoomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс номера',
                'verbose_name_plural': 'Классы номеров',
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='accommodation_images/', verbose_name='Изображение')),
                ('image_type', models.CharField(blank=True, choices=[('c', 'карточка'), ('s', 'слайдер')], default='s', max_length=1, verbose_name='тип')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объекта',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.country', verbose_name='Страна'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Регион')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_regions', to='accommodations.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='AccommodationFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed_desc', models.TextField(blank=True, verbose_name='Описание')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation', verbose_name='Объект')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.country', verbose_name='Страна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Характеристика объекта',
                'verbose_name_plural': 'Характеристики объекта',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.region', verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='AccommodationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Стоимость суток')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_costs', to='accommodations.accommodation', verbose_name='Объект')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomclass', verbose_name='Класс номера')),
            ],
            options={
                'verbose_name': 'Стоимость номера',
                'verbose_name_plural': 'Стоимость номеров',
            },
        ),
        migrations.CreateModel(
            name='AccommodationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.PositiveIntegerField(default=0, verbose_name='Число свободных номеров')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation', verbose_name='Объект')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomclass', verbose_name='Класс номера')),
            ],
            options={
                'verbose_name': 'Наличие номера',
                'verbose_name_plural': 'Наличие номеров',
            },
        ),
    ]
