# Generated by Django 5.2 on 2026-03-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('nights', models.PositiveIntegerField(default=3, verbose_name='Число ночей')),
                ('guests', models.PositiveIntegerField(default=1, verbose_name='Число гостей')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation', verbose_name='Объект')),
                ('room_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomclass', verbose_name='Класс номера')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзина',
                'ordering': ('id',),
            },
        ),
    ]
