# Generated by Django 5.2 on 2026-01-30 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='room_class',
            field=models.ForeignKey(choices=[(1, 'single'), (2, 'standard'), (3, 'comfort'), (4, 'deluxe')], on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomclass', verbose_name='Класс номера'),
        ),
    ]
