# Generated by Django 5.2 on 2026-02-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('carts', '0002_alter_cart_room_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Число гостей'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='nights',
            field=models.PositiveIntegerField(default=3, verbose_name='Число ночей'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='room_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodations.roomclass', verbose_name='Класс номера'),
        ),
    ]
