# Generated by Django 5.2 on 2026-02-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, verbose_name='город')),
                ('phone', models.CharField(max_length=64, verbose_name='телефон')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
